### ISSUE TITLE
Missing win64 build of 4.2.5

### ISSUE THREAD

**Issue by tkelman** [AnacondaRecipes/zeromq-feedstock#3]
Did something fail to go through? https://anaconda.org/anaconda/zeromq/files

**Comment by jjhelmus** [comment]
@mingwandroid are you aware of any blockers for releasing zeromq 4.2.5 for win-64?

**Comment by mingwandroid** [comment]
Our mirroring may have. I'll look later

**Comment by mingwandroid** [comment]
Sorry about that @tkelman, I've uploaded these now, I suspect I had too many spinning plates when I was looking into zeromq!

**Comment by tkelman** [comment]
Great, thanks, updating my envs can stop downgrading this in the process of switching between c-f and defaults. Updates are seeing it but I guess that anaconda.org page takes some time to refresh?

**Comment by mingwandroid** [comment]
The `anaconda` channel isn't something you should use, it exists to aid our enterprise customers when mirroring and AFAIK we *never* mention it. Seems people just found it and started using it!

It is mirrored once a day I believe but worse than that, it mixes packages from the old `free` channel with the new `main` channel ignoring that we want `main` to have higher priority than `free`.

`defaults` is the right (meta-)channel to use. It always refers to `https://repo.continuum.io/pkgs/main` and `https://repo.continuum.io/pkgs/free` (and `msys2` if you're on Windows).

**Comment by tkelman** [comment]
I was using that page for reference because it's a nicer UI and the only defaults-relevant-looking result from https://anaconda.org/search?q=zeromq. The repodata's obviously the definitive source of info, but not very nice for human consumption. Will keep in mind that "anaconda" is a delayed mirror - most c-f uploads I tend to see immediately on `https://anaconda.org/conda-forge/.../files`

**Comment by mingwandroid** [comment]
Yup, for `conda-forge` `https://anaconda.org` *is* the source, for `defaults` it's `https://repo.continuum.io/pkgs`
